# Docker Compose for Local Development
# Chỉ chạy database, BE và FE chạy local với yarn dev

services:
  db:
    image: postgres:15
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-todo_nest}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  postgres_data_dev:
